---
- name: Install jq
  yum:
    name: jq
    state: installed

- name: Install easy-rsa
  yum:
    name: easy-rsa
    state: installed

- name: Download and install Packer
  unarchive:
    src: '{{ okd_lab_packer_url }}'
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes

- name: Download and install Terraform
  unarchive:
    src: '{{ okd_lab_terraform_url }}'
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes

- name: Initialize Terraform workspace
  command: terraform init
  become_user: lab
  args:
    chdir: /home/lab

- name: Create plugin directory
  file:
    path: ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/{{ okd_lab_terraform_kvm_version }}/linux_amd64
    state: directory
    mode: '0755'
  become_user: lab

- name: Download and install Terraform KVM plugin
  unarchive:
    src: '{{ okd_lab_terraform_kvm_url }}'
    dest: ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/{{ okd_lab_terraform_kvm_version }}/linux_amd64
    mode: '0755'
    remote_src: yes
  become_user: lab

- name: Install python openshift
  shell: |
    pip3 install openshift --user lab

- name: Install community.kubernetes collection
  shell: |
    ansible-galaxy collection install community.kubernetes
  become_user: lab

- name: Install community.okd collection
  shell: |
    ansible-galaxy collection install community.okd
  become_user: lab

- name: Install ommunity.crypto collection
  shell: |
    ansible-galaxy collection install community.crypto
  become_user: lab
