---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-ceph-file
