apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-image-registry
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block
  