---
- name: Toolbox
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'toolbox.yaml') | from_yaml }}"
    wait: true

- name: Ceph BlockPool
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-block-pool.yaml') | from_yaml }}"
    wait: true

- name: Ceph Block Storageclass
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-block-storageclass.yaml') | from_yaml }}"
    wait: true

- name: Ceph ObjectStore
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-object-store.yaml') | from_yaml }}"
    wait: true

- name: Ceph ObjectStore Route
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-object-route.yaml') | from_yaml }}"
    wait: true

- name: Ceph Object Storageclass
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-object-storageclass.yaml') | from_yaml }}"
    wait: true

- name: Ceph Object Bucket Claim
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-object-bucket-claim.yaml') | from_yaml }}"
    wait: true

- name: Ceph ObjectStore Service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-object-store-service.yaml') | from_yaml }}"
    wait: true

- name: Ceph File
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-file.yaml') | from_yaml }}"
    wait: true
  tags: setup

- name: Ceph File Storageclass
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ceph-file-storageclass.yaml') | from_yaml }}"
    wait: true

- name: Dashboard Route
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'route.yaml') | from_yaml }}"
    wait: true
