apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: rook-ceph-webhook
  namespace: rook-ceph
webhooks:
  - name: rook-ceph-admission-controller.rook-ceph.svc
    rules:
      - apiGroups:   ["ceph.rook.io"]
        apiVersions: ["v1"]
        operations:  ["CREATE","UPDATE","DELETE"]
        resources:   ["cephclusters"]
    clientConfig:
      service:
        name: rook-ceph-admission-controller
        namespace: rook-ceph
        path: /validate-ceph-rook-io-v1-cephcluster
      caBundle: {{ ca_bundle.stdout }}
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
  - name: rook-ceph-admission-controller.rook-ceph.svc
    rules:
      - apiGroups:   ["ceph.rook.io"]
        apiVersions: ["v1"]
        operations:  ["CREATE","UPDATE","DELETE"]
        resources:   ["cephblockpools"]
    clientConfig:
      service:
        name: rook-ceph-admission-controller
        namespace: rook-ceph
        path: /validate-ceph-rook-io-v1-cephblockpool
      caBundle: {{ ca_bundle.stdout }}
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    timeoutSeconds: 5

