---
- name: Install jq
  dnf:
    name: jq
    state: installed

- name: Add Hashicorp Repository
  shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Terraform
  shell: dnf install -y terraform

- name: Install Packer
  shell: dnf install -y packer

- name: Initialize Terraform workspace
  command: terraform init
  become_user: lab
  args:
    chdir: /home/lab

- name: Install openshift python package
  pip:
    name: openshift
    umask: "0022"
  become: True

- name: Install epel-release
  dnf:
    name: epel-release
    state: latest

- name: Install easy-rsa
  dnf:
    name: easy-rsa
    state: latest
