---
- name: Init bootstrap
  command: terraform init
  args:
    chdir: ~/okd-lab/terraform/bootstrap
  tags: 
    - bootstrap-apply
    - apply

- name: Apply bootstrap
  terraform:
    project_path: '~/okd-lab/terraform/bootstrap'
    state: present
  tags: 
    - bootstrap-apply
    - apply

- name: Destroy bootstrap
  terraform:
    project_path: '~/okd-lab/terraform/bootstrap'
    state: absent
  tags: 
    - bootstrap-destroy
    - destroy

- name: Apply master
  terraform:
    project_path: '~/okd-lab/terraform/master'
    force_init: true
    state: present
  tags: 
    - master-apply
    - apply

- name: Destroy master
  terraform:
    project_path: '~/okd-lab/terraform/master'
    state: absent
  tags: 
    - master-destroy
    - destroy

- name: Apply worker
  terraform:
    project_path: '~/okd-lab/terraform/worker'
    force_init: true
    state: present
  tags: 
    - worker-apply
    - apply

- name: Destroy worker
  terraform:
    project_path: '~/okd-lab/terraform/worker'
    state: absent
  tags: 
    - worker-destroy
    - destroy
