spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  replicas: 3