---
- name: Install packages
  yum:
    name: ['python3-lxml']
    state: present

- name: Enable dnsmasq
  copy:
    src: 00-dnsmasq.conf
    dest: /etc/NetworkManager/conf.d/00-dnsmasq.conf
  become_user: root

- name: Enable okd-lab dns
  copy:
    src: 00-okd-lab.conf
    dest: /etc/NetworkManager/dnsmasq.d/00-okd-lab.conf
  become_user: root

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  become_user: root

- name: Define network okd
  virt_net:
    command: define
    name: "okd"
    xml: "{{ lookup('file', 'okd.xml') }}"

- name: Activate network okd
  virt_net:
    state: active
    name: "okd"

- name: Autostart network okd
  virt_net:
    autostart: yes
    name: "okd"

- name: Delete network default
  virt_net:
    state: absent
    name: "default"
