---
- name: Install tftp
  dnf:
    name: tftp
    state: installed

- name: Install tftp-server
  dnf:
    name: tftp-server
    state: installed

- name: Relax permissions in /var/lib/tftpboot
  file:
    path: /var/lib/tftpboot
    state: directory
    mode: '777'

- name: Install xinetd
  dnf:
    name: xinetd
    state: installed

- name: Start service xinetd
  service:
    name: xinetd
    state: started

- name: Enable service xinetd
  service:
    name: xinetd
    enabled: yes

- name: Allow 69/udp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=tftp

- name: Restart service firewalld
  service:
    name: firewalld
    state: restarted

- name: Publish tftp
  copy: 
    src:  tftp 
    dest: /etc/xinetd.d/tftp

- name: Retart service xinetd
  service:
    name: xinetd
    state: started

