---
- name: Create SSH key
  user:
    name: lab
    generate_ssh_key: yes
    ssh_key_comment: 'lab@lab.okd.example.com'
    ssh_key_bits: 2048
    ssh_key_file: "/home/lab/okd-lab/.ssh/id_rsa"
  become_user: lab

- name: Prepare authorized key
  authorized_key:
    user: lab
    state: present
    path: ~/okd-lab/.ssh/authorized_keys
    key: "{{ lookup('file', '/home/lab/okd-lab/.ssh/id_rsa.pub') }}"
  become_user: lab

- name: Prepare ssh config
  template:
    src: config.j2
    dest: /home/lab/.ssh/config
    owner: lab
    group: lab
    mode: '0600'
  become_user: lab
    
- name: Check that the somefile.conf exists
  stat:
    path: "/home/lab/okd-lab/.ssh/id_rsa"
  register: stat_result

- name: Create the file, if it doesnt exist already
  file:
    path: "/home/lab/okd-lab/.ssh/id_rsa"
    mode: 0600
  when: stat_result.stat.exists
