---
- name: Install bind-utils
  yum:
    name: bind-utils
    state: installed

- name: Install haproxy
  yum:
    name: haproxy
    state: installed

- name: Install policycoreutils-python
  yum:
    name: policycoreutils-python
    state: installed

- name: Publish haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root

- name: Start service haproxy
  service:
    name: haproxy
    state: started

- name: Enable service haproxy
  service:
    name: haproxy
    enabled: yes

- name: Allow 80/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="80/tcp"

- name: Allow 8080/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="8080/tcp"

- name: Allow 443/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="443/tcp"

- name: Allow 6443/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="6443/tcp"

- name: Allow 22623/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="22623/tcp"

- name: Allow 9000/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="9000/tcp"

- name: Reload firewall
  command: firewall-cmd --reload

