---
- name: Install bind-utils
  yum:
    name: bind-utils
    state: installed

- name: Install haproxy
  yum:
    name: haproxy
    state: installed

- name: Allow 80/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=http

- name: Allow 443/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=https

- name: Allow 8080/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="8080/tcp"

- name: Allow 6443/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="6443/tcp"

- name: Allow 22623/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="22623/tcp"

- name: Allow 9000/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="9000/tcp"

- name: Reload firewall
  command: firewall-cmd --reload

- name: Copy server.crt
  copy:
    src: lb-server.crt
    dest: /etc/pki/tls/certs/lb-server.crt

- name: Copy server.key
  copy:
    src: lb-server.key
    dest: /etc/pki/tls/private/lb-server.key

- name: Prepare certs
  shell: 'cat /etc/pki/tls/certs/lb-server.crt /etc/pki/tls/private/lb-server.key > /etc/pki/tls/private/lb-server.pem'

- name: setsebool
  command: setsebool -P haproxy_connect_any 1

- name: Publish haproxy.cfg
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root

- name: Start service haproxy
  service:
    name: haproxy
    state: started

- name: Enable service haproxy
  service:
    name: haproxy
    enabled: yes
