---
- name: Copy common resources to remote
  copy:
    src: '{{ item }}'
    dest: /tmp/{{ item }}
  with_items:
    - common.yaml
    - crds.yaml

- name: Apply common resources
  command: oc apply -f /tmp/{{ item }}
  with_items:
    - common.yaml
    - crds.yaml

- name: Cleanup common resources
  file:
    path: /tmp/{{ item }}
    state: absent
  with_items:
    - common.yaml
    - crds.yaml

- name: Get ca bundle for validating webhook
  shell: |
    oc get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
  register: ca_bundle  

- name: Apply ValidatingWebhookConfiguration
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'webhook-config.yaml') | from_yaml }}"

- name: Copy common resources to remote
  copy:
    src: '{{ item }}'
    dest: /tmp/{{ item }}
  with_items:
    - operator-openshift.yaml
    - rbac.yaml
    - cluster.yaml

- name: Apply Operator
  command: oc apply -f /tmp/operator-openshift.yaml

- name: Wait for Operator to complete
  command: oc rollout status -w deployment/rook-ceph-operator -n rook-ceph

- name: Apply Operator
  command: oc apply -f /tmp/rbac.yaml
  tags: cluster

- name: Apply Cluster
  command: oc apply -f /tmp/cluster.yaml

- name: Cleanup common resources
  file:
    path: /tmp/{{ item }}
    state: absent
  with_items:
    - operator-openshift.yaml
    - rbac.yaml
    - cluster.yaml
