---
#######################################################################
#
# Change this IP to a DNS/NTP server you want to use as forwarder
#
#######################################################################

# Hetzner DNS Server
okd_lab_bind_forwarder: '213.133.98.98'

# Hetzner NTP Server
okd_lab_ntp_forwarder: 'ntp1.hetzner.de'


#########################################################################
#
# Change these settings if you intend to install a different OKD version
#
#########################################################################

# OKD installation version
okd_lab_install_okd_version: 4.8.0-0.okd-2021-10-24-061736

# Fedora CoreOS installation version and stream
okd_lab_install_fcos_stream: 'stable' 
okd_lab_install_fcos_version: '34.20210626.3.1'


#########################################################################
#
# Change these settings if you intend to install different cli versions
#
#########################################################################

okd_lab_clis_kustomize: v4.4.0
okd_lab_clis_argocd: v2.1.5
okd_lab_clis_argo: v3.2.2
okd_lab_clis_argo_events: v1.5.0
okd_lab_clis_argo_rollouts: v1.1.0
okd_lab_clis_tekton: 0.21.0
okd_lab_clis_helm: v3.7.1
okd_lab_clis_kubeseal: v0.16.0
okd_lab_clis_kyverno: v1.5.1
okd_lab_clis_k9s: v0.24.15
okd_lab_clis_github: 2.0.0


#########################################################################
#
# Change this setting if you intend to mirror a different CentOS version
#
#########################################################################

# CentOS version
okd_lab_mirror_centos_version: '8.4.2105'


#######################################################################
#
# Do not change from here until you know what you do :-)
#
#######################################################################

# Base URL for Fedora CoreOS downloads
okd_lab_fedora_coreos_base_url: 'https://builds.coreos.fedoraproject.org/prod/streams/{{ okd_lab_install_fcos_stream }}/builds/{{ okd_lab_install_fcos_version }}/x86_64/fedora-coreos-{{ okd_lab_install_fcos_version }}-'

# OKD Client
okd_lab_okd_oc_client_archive: 'openshift-client-linux-{{ okd_lab_install_okd_version }}.tar.gz'  
okd_lab_okd_oc_client: 'https://github.com/openshift/okd/releases/download/{{ okd_lab_install_okd_version }}/openshift-client-linux-{{ okd_lab_install_okd_version }}.tar.gz'  

# OKD Installer
okd_lab_okd_installer_archive: 'openshift-install-linux-{{ okd_lab_install_okd_version }}.tar.gz'  
okd_lab_okd_installer: 'https://github.com/openshift/okd/releases/download/{{ okd_lab_install_okd_version }}/openshift-install-linux-{{ okd_lab_install_okd_version }}.tar.gz'  

# CentOS Mirror
okd_lab_centos_mirror: 'http://mirror.netcologne.de/centos/{{ okd_lab_mirror_centos_version }}/isos/x86_64'
okd_lab_centos_iso: 'CentOS-{{ okd_lab_mirror_centos_version }}-x86_64-dvd1.iso'

# Unique name of this installation
okd_lab_install_okd_name: "{{ okd_lab_install_okd_version | regex_replace('[.]', '-') }}"


# Network
okd_lab_network_dns_ip: 10.0.0.1
okd_lab_network_subnet_mask: 255.255.255.0
okd_lab_network_gateway: 10.0.0.1

# Bastion
okd_lab_host_bastion_ip: 10.0.0.2

# Mirror URL's
okd_lab_mirror_fcos_url: http://{{ okd_lab_host_bastion_ip }}/fcos/{{ okd_lab_install_okd_name }}
okd_lab_installer_ignition_url: http://{{ okd_lab_host_bastion_ip }}/ignition/{{ okd_lab_install_okd_name }}

# 389 Directory Server
okd_lab_directory_root_password: 'directory'
okd_lab_directory_hostname: 'ldap.okd.example.com'

# GitLab
okd_lab_gitlab_container_image: 'docker.io/gitlab/gitlab-ce:14.4.1-ce.0'

okd_lab_gitlab_hostname: gitlab.okd.example.com
okd_lab_gitlab_url: https://{{ okd_lab_gitlab_hostname }}
okd_lab_gitlab_ip: 10.88.0.40
okd_lab_gitlab_root_user: 'root'
okd_lab_gitlab_root_password: 'rootroot'
okd_lab_gitlab_root_email: 'gitlabadmin@example.com'
okd_lab_gitlab_registry_hostname: registry.okd.example.com
okd_lab_gitlap_ldap_hostname: 'ldap.okd.example.com'
okd_lab_gitlab_registry_url: https://{{ okd_lab_gitlab_registry_hostname }}
okd_lab_gitlab_grafana_admin_password: admin
okd_lab_gitlab_lab_token: "{{ lookup('file', '~/github/okd-lab/.secrets/gitlab-lab-token') }}"

# Artifactory
okd_lab_artifactory_image: "releases-docker.jfrog.io/jfrog/artifactory-oss:7.27.9"
okd_lab_artifactory_postgres_image: "postgres:10.12"

okd_lab_artifactory_hostname: "artifactory.okd.example.com"
okd_lab_artifactory_url: "https://{{ okd_lab_artifactory_hostname }}"
okd_lab_artifactory_ip: 10.88.0.36
okd_lab_artifactory_postgres_ip: 10.88.0.37
okd_lab_artifactory_api_url: "http://{{ okd_lab_artifactory_ip }}:8082/artifactory/api"
okd_lab_artifactory_local_admin_username: "admin"
okd_lab_artifactory_local_admin_password: "password"
okd_lab_artifactory_java_opts: "-Xms512m -Xmx2g"

# Quay/Clair
okd_lab_quay_image: quay.io/projectquay/quay:3.6-unstable
okd_lab_quay_redis_image: docker.io/redis:5.0.7
okd_lab_quay_postgres_image: docker.io/postgres:10.12
okd_lab_quay_clair_image: quay.io/projectquay/clair:4.3.0
okd_lab_quay_swagger_image: docker.io/swaggerapi/swagger-ui:v3.44.1

okd_lab_quay_hostname: quay.okd.example.com
okd_lab_quay_url: https://{{ okd_lab_quay_hostname }}
okd_lab_quay_api_url: '{{ okd_lab_quay_url }}/api/v1'
okd_lab_quay_ip: 10.88.0.32
okd_lab_quay_redis_ip: 10.88.0.31
okd_lab_quay_mirror_ip: 10.88.0.33
okd_lab_quay_postgres_ip: 10.88.0.30
okd_lab_quay_config_ip: 10.88.0.34
okd_lab_quay_swaggger_ip: 10.88.0.35
okd_lab_quay_container_image: '{{ okd_lab_quay_url }}/api/v1'
okd_lab_quay_scanner_endpoint: http://{{ okd_lab_clair_ip }}:8081
okd_lab_quay_mail_default_sender: quay-admin@example.com
okd_lab_quay_ldap_url: "ldaps://{{ okd_lab_directory_hostname }}" 
okd_lab_clair_ip: 10.88.0.21
okd_lab_clair_postgres_ip: 10.88.0.20
okd_lab_quay_lab_token: "{{lookup('file', '{{ playbook_dir }}/../../.secrets/quay-lab-token')}}"
okd_lab_quay_redis_password: "strongpassword"
okd_lab_quay_postgres_user: "user"
okd_lab_quay_postgres_password: "pass"
okd_lab_quay_config_password: "secret"
okd_lab_clair_postgres_user: "user"
okd_lab_clair_postgres_password: "pass"
okd_lab_clair_psk: "NmNhZWY3MWowNzhnYQ=="
