---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-grafana-ds-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-grafana-ds
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadatasources
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-grafana-ds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-grafana-ds
subjects:
  - kind: ServiceAccount
    name: patch-grafana-ds-job