apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: policy-reporter

resources:
- namespace.yaml
- rbac.yaml
- https://gitlab.okd.example.com/lab/okd-lab.git//gitops/manifests/policy-reporter?ref=HEAD
- monitoring.yaml
- route.yaml
