---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kyverno
spec:
  host: kyverno.apps.okd.example.com
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: policy-reporter-ui
    weight: 100
  wildcardPolicy: None
