---
- name: Install nginx
  dnf:
    pkg: nginx
    state: installed

- name: Allow 80/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=http

- name: Allow 443/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=https

- name: Restart service firewalld
  service:
    name: firewalld
    state: restarted

- name: Allow httpd_can_network_connect for nginx
  command: setsebool -P httpd_can_network_connect 1

- name: Publish nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0660'

- name: Copy server.crt
  copy:
    src: bastion-server.crt
    dest: /etc/pki/tls/certs/bastion-server.crt

- name: Copy server.key
  copy:
    src: bastion-server.key
    dest: /etc/pki/tls/private/bastion-server.key

- name: Copy config files
  template:
    src: '{{ item }}.conf.j2'
    dest: /etc/nginx/conf.d/{{ item }}.conf
    owner: root
    group: root
    mode: '0660'
  with_items:
  - gitlab
  - registry
  - quay
  - artifactory

- name: Start service nginx
  service:
    name: nginx
    state: started

- name: Enable service nginx
  service:
    name: nginx
    enabled: yes

- name: Create ignition directory
  file: 
    path: /usr/share/nginx/html/ignition
    state: directory
    mode: '777'

- name: Create fcos directory
  file: 
    path: /usr/share/nginx/html/fcos
    state: directory
    mode: '777'

- name: Remove files
  file:
    path: /usr/share/nginx/html/{{ item.file }}
    state: absent
  with_items:
    - { file: 'en-US' }
    - { file: 'icons' }
    - { file: 'img' }
    - { file: '50x.html' }
    - { file: '404.html' }
    - { file: 'nginx-logo.png' }
    - { file: 'poweredby.png' }
    - { file: 'modules' }
    - { file: 'index.html' }
