---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:anyuid-tekton-triggers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: tekton-triggers-controller
  namespace: tekton-pipelines
- kind: ServiceAccount
  name: tekton-triggers-webhook
  namespace: tekton-pipelines
- kind: ServiceAccount
  name: tekton-triggers-core-interceptors
  namespace: tekton-pipelines
