---
- name: Install bind
  yum:
    name: bind
    state: installed

- name: Install bind-utils
  yum:
    name: bind-utils
    state: installed

- name: Allow 53/udp/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-service=dns

- name: Reload firewall
  command: firewall-cmd --reload

- name: Publish named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0660'

- name: Publish named.conf.local
  copy:
    src: named.conf.local
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: '0660'

- name: Publish named.rfc1912.zones
  copy:
    src: named.rfc1912.zones
    dest: /etc/named.rfc1912.zones
    owner: root
    group: named
    mode: '0660'

- name: Create zones directory
  file:
    path: /etc/named/zones
    state: directory

- name: Publish zones
  copy:
    src: '{{ item }}'
    dest: /etc/named/zones/{{ item }}
    owner: root
    group: named
    mode: '0660'
  with_items:
  - db.10.0.0
  - db.example.com

- name: Start service named
  service:
    name: named
    state: started

- name: Enable service named
  service:
    name: named
    enabled: yes

- name: Change DNS IP with NetworkManager
  nmcli:
    conn_name: "eth0"
    type: ethernet
    dns4:
      - "10.0.0.2"
    state: present

- name: Change DNS search with NetworkManager
  nmcli:
    conn_name: "eth0"
    type: ethernet
    dns4_search:
      - "example.com"
    state: present

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
