---
#######################################################################
#
# Apply (provision) Cluster with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags apply
#
# Destroy (unprovision) Cluster with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags destroy
#
#
# Apply Bootstrap with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags bootstrap-apply
#
# Destroy Bootstrap with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags bootstrap-destroy
#
# Apply Master with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags master-apply
#
# Destroy Master with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags master-destroy
#
# Apply Worker with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags worker-apply
#
# Destroy Worker with Terraform
# ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags worker-destroy
#######################################################################
- hosts: localhost
  connection: local
  become_user: lab
  become: yes
  gather_facts: no
  roles:
    - okd-cluster
