---
######################################################################################
#
# Setup OKD installation environment
# ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags env-setup
#
# Cleanup OKD installation environment
# ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags env-cleanup
#
#
# Setup OKD Installer to use Registry Mirror
# ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags installer-setup
# Pleae Note! You have to mirror the registry first!
#
######################################################################################
- hosts: bastion
  vars_files:
    - vars/vars.yaml
  gather_facts: no
  become_user: lab
  become: true
  become_flags: '-i'  
  roles:
    - okd-env
    - okd-installer
