---
- name: Allow 2222/tcp
  command: firewall-cmd --zone=public --permanent --add-port=2222/tcp

- name: Create Directories
  file:
    path: '{{ item.dir }}'
    state: directory
  with_items:
    - { dir: '/var/opt/gitlab/config' }
    - { dir: '/var/opt/gitlab/config/trusted-certs' }
    - { dir: '/var/opt/gitlab/logs' }
    - { dir: '/var/opt/gitlab/data' }
    - { dir: '/var/opt/gitlab/registry' }

- name: Prepare directoy
  command: chmod -R go+w /var/opt/gitlab/registry

- name: Copy ca.crt for Grafana
  copy:
    src: /etc/ca.crt
    dest: /var/opt/gitlab/config/trusted-certs/ca.pem
    remote_src: yes
    mode: '0644'

- name: Copy ca.crt for LDAP
  copy:
    src: /etc/ca.crt
    dest: /var/opt/gitlab/config/ca.pem
    remote_src: yes
    mode: '0644'

- name: Copy gitlab config
  template:
    src: gitlab.rb.j2
    dest: /var/opt/gitlab/config/gitlab.rb

- name: Copy gitlab service
  template: 
    src:  container-gitlab.service.j2 
    dest: /etc/systemd/system/container-gitlab.service

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Start container-gitlab.service
  systemd:
    name: container-gitlab.service
    state: started
    enabled: yes
