---
- name: Create Directories
  file:
    path: '{{ item.dir }}'
    state: directory
  with_items:
    - { dir: '/var/opt/clair/postgres' }
    - { dir: '/var/opt/clair/config' }

- name: Setfacl for postgres storage
  command: setfacl -m u:26:-wx /var/opt/clair/postgres/

- name: Copy ca.crt
  copy:
    src: /etc/ca.crt
    dest: /var/opt/clair/config/ca.crt
    remote_src: yes

- name: Copy services
  template:
    src: '{{ item }}.j2'
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - container-clair-postgres.service
    - container-clair-clair.service

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Copy clair config
  template:
    src: 'config.yaml.j2'
    dest: /var/opt/clair/config/config.yaml

- name: Relax clair config permissions
  shell: chmod -R 777 /var/opt/clair/config
  args:
    warn: false

- name: Start container-clair-postgres.service
  systemd:
    name: container-clair-postgres.service
    state: started
    enabled: yes

- name: Pause 30 seconds
  pause:
    seconds: '30'

- name: Install postgres extension
  shell: podman exec -it clair-postgres /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"" | psql -d clair -U user'

- name: Start container-clair-clair.service
  systemd:
    name: container-clair-clair.service
    state: started
    enabled: yes

