apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- oauth-client.yaml
- sso.yaml
- https://gitlab.okd.example.com/lab/okd-lab.git//gitops/manifests/argocd?ref=HEAD
- rbac.yaml
- https://gitlab.okd.example.com/lab/okd-lab.git//gitops/manifests/applicationset?ref=HEAD
- monitoring.yaml
- alerts.yaml
- route.yaml
- repo-okd-lab.yaml

- project-runtime.yaml
- app-argocd.yaml
- app-sealed-secrets.yaml

- project-config.yaml
- app-config-bootstrap.yaml


patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-rbac-cm
  data:
    policy.csv: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, awesome-admins, role:admin
      g, awesome-developers, role:admin

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-cmd-params-cm
  data:
    server.insecure: "true"

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-cm
  data:
    url: https://argocd.apps.okd.example.com
    dex.config: |
        staticClients:
          - id: argo-workflows-sso
            name: Argo Workflow
            redirectURIs:
              - https://argo.apps.okd.example.com/oauth2/callback
            secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        connectors:
          - type: openshift
            id: openshift
            name: OpenShift
            config:
              issuer: https://api.okd.example.com:6443
              clientID: argocd-oauth-client
              clientSecret: argocd
              redirectURI: https://argocd.apps.okd.example.com/api/dex/callback
              insecureCA: true
              groups:
               - admins
               - awesome-admins
               - awesome-developers

- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: argocd-dex-server
    annotations:
      serviceaccounts.openshift.io/oauth-redirecturi.dex: https://argocd.apps.okd.example.com/api/dex/callback

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-tls-certs-cm
  data:
    gitlab.okd.example.com: |-
      -----BEGIN CERTIFICATE-----
      MIIDSDCCAjCgAwIBAgIULqLTieg864a/Sgmds8r7x6iXQp4wDQYJKoZIhvcNAQEL
      BQAwFTETMBEGA1UEAwwKRXhhbXBsZS1DQTAeFw0yMTAzMjExNTIzMDJaFw0zMTAz
      MTkxNTIzMDJaMBUxEzARBgNVBAMMCkV4YW1wbGUtQ0EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDikS8Bf1nKVGgONiVawJzfNl9SvXE6cF2PY2NJS0Q9
      SnMLe8iM8HENtu+x6Iv8LK5AcFYvx8finmvH7y2dn4ft65gFJfCUECMK30NtCrEU
      bovJAEQ3WrDBwhSYV0JhtkN7zwnBCiOtF6FFBNblOAUIj6Z7tCgOZHXwtFLt5UK1
      CTX/al/R39awUL0T1iW0BSR4G8VTFVeZOSFtDIXOFzkyo5PsMVd6MIyJn6FNhn+5
      daXlJBEQOY+bZA3MO33tKFEQapsLyCwbv0xsTpfjKrTWSw5TchITHOOWF8iXyxee
      t1MU0eDC89aKVvND1oCGki1AcntRQxnbZP4VgJ7BbvkXAgMBAAGjgY8wgYwwHQYD
      VR0OBBYEFG+UKwkxzTKJE13AS2WQuMWYHBzHMFAGA1UdIwRJMEeAFG+UKwkxzTKJ
      E13AS2WQuMWYHBzHoRmkFzAVMRMwEQYDVQQDDApFeGFtcGxlLUNBghQuotOJ6Dzr
      hr9KCZ2zyvvHqJdCnjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG
      9w0BAQsFAAOCAQEAWBDI4Kehf+Apt1tfKQgWWWjJRI9avDTZI3rF94rbZgPxSzzW
      uvrC4+hJmMkUT1+tmR1+85hv47hOLWXJVTaBCb/H+jyjKvHdQcjHK5LEPMY2kPjo
      u+6pd5IQSuVzJ4IkuFPpmEL91vvNGLaVC+kiqfTnrUDLxgMSwwk4+SY4n6dLjiz8
      uz/QARTdnviCL/3lQgoDLahZN2TDtItXZ9niikhVJgvgavYgtZrKWwdqO1MOWNW5
      ETSEH/VycE1dRrYDZT9LhbemMA3VfzAsSb1kO5nG9oIsi4RwwCv1EuxjHhMk0sy3
      1ONXTcAtHi/FwgvhrOEtuzYB2XOMUR37p/ZdzQ==
      -----END CERTIFICATE-----

# Fix remove user 999 
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: argocd-redis
  spec:
    template:
      spec:
        securityContext:
          runAsUser:

- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: argocd-dex-server
  spec:
    template:
      spec:
        containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-workflows-sso
                  key: client-secret
