---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-prometheus-k8s-read
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-prometheus-k8s-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-prometheus-k8s-read
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring