---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: argo-workflows-controller-metrics
  name: argo-workflows-controller-metrics
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: workflow-controller
      app.kubernetes.io/instance: argo-workflows
