---
- name: Create Directories
  file:
    path: '{{ item.dir }}'
    state: directory
  with_items:
    - { dir: '/var/opt/quay/postgres' }
    - { dir: '/var/opt/quay/config' }
    - { dir: '/var/opt/quay/storage' }

- name: Setfacl for postgres storage
  command: setfacl -m u:26:-wx /var/opt/quay/postgres/

- name: Setfacl for quay storage
  command: setfacl -m u:1001:-wx /var/opt/quay/storage/

- name: Copy ca.crt
  copy:
    src: /etc/ca.crt
    dest: /var/opt/quay/config/ldap.crt
    remote_src: yes

- name: Copy services
  template:
    src: '{{ item }}.j2'
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - container-quay-postgres.service
    - container-quay-redis.service
    - container-quay-config.service 
    - container-quay-quay.service
    - container-quay-mirror.service
    - container-quay-swagger.service

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Start container-quay-postgres.service
  systemd:
    name: container-quay-postgres.service
    state: started
    enabled: yes

- name: Pause 60 seconds
  pause:
    seconds: '60'

- name: Install postgres extension
  shell: podman exec -it quay-postgres /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d quay -U user'

- name: Start container-quay-redis.service
  systemd:
    name: container-quay-redis.service
    state: started
    enabled: yes

- name: Pause 60 seconds
  pause:
    seconds: '60'

- name: Copy quay config
  template:
    src: config.yaml.j2
    dest: /var/opt/quay/config/config.yaml

- name: Start container-quay-quay.service
  systemd:
    name: container-quay-quay.service
    state: started
    enabled: yes

- name: Pause 30 seconds
  pause:
    seconds: '30'

- name: Add administrator
  shell: |
    podman exec -it quay-postgres /bin/bash -c "psql -d quay -U user -c \"INSERT INTO public.user VALUES (0,'965d4ed1-f6c9-4078-acd3-108399fbcdb2','administrator','$2a$12$2NfONl3aVhM3XJqGhIWfWuESg32jKKjepRkz3RUsEbcdaVaGY46pe','administrator-quay@example.com',true,null,false,false,false,0,'2021-02-02 15:25:07.262604',1209600,true,null,null,null,null,null,null,'2021-02-02 15:25:07.2626',null)\""

- name: Pause 60 seconds
  pause:
    seconds: '60'

- name: Start container-quay-mirror.service
  systemd:
    name: container-quay-mirror.service
    state: started
    enabled: yes

- name: Start container-quay-swagger.service
  systemd:
    name: container-quay-swagger.service
    state: started
    enabled: yes
