---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-object
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: rook-ceph-object-store
  objectStoreNamespace: rook-ceph
  region: eu-west-1
