apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
- https://gitlab.okd.example.com/lab/okd-lab.git//gitops/manifests/rook-ceph/operator?ref=HEAD
- route.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rook-ceph
    labels:
      openshift.io/cluster-monitoring: "true"
