---
- name: Allow insecure quay registry 
  command: "oc patch image.config.openshift.io cluster --type merge -p '{\"spec\":{\"registrySources\":{\"insecureRegistries\":[\"quay.okd.example.com:5000\"]}}}'"

- name: Temporary registry sorage 
  command: "oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"managementState\":\"Managed\",\"storage\":{\"emptyDir\":{}}}}'"

- name: Label master as infra nodes
  command: oc label nodes master-{{ item.master }}.okd.example.com node-role.kubernetes.io/infra=""
  with_items:
    - { master: '0' }
    - { master: '1' }
    - { master: '2' }

- name: Disable masters schedulable
  command: oc patch scheduler cluster --patch '{"spec":{"mastersSchedulable":false}}' --type=merge

- name: Stick router to masters
  command: oc patch -n openshift-ingress-operator ingresscontroller default --patch '{"spec":{"nodePlacement":{"nodeSelector":{"matchLabels":{"node-role.kubernetes.io/infra":""}},"tolerations":[{"key":"node.kubernetes.io/unschedulable","effect":"NoSchedule"},{"key":"node-role.kubernetes.io/master","effect":"NoSchedule"}]}}}' --type=merge

- name: Enable imagepruners
  command: oc patch imagepruners.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"schedule":"0 0 * * *","suspend":false,"keepTagRevisions":3,"keepYoungerThan":60,"resources":{},"affinity":{},"nodeSelector":{},"tolerations":[],"startingDeadlineSeconds":60,"successfulJobsHistoryLimit":3,"failedJobsHistoryLimit":3}}'

