---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
data:
  config.yaml: |
    prometheus:
      nodeSelector:
              node-role.kubernetes.io/infra: ""
      retention: 12h
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          resources:
            requests:
              storage: 20Gi
    thanosRuler:
      nodeSelector:
              node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          resources:
            requests:
              storage: 20Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
