{
 "title": "PolicyReports",
 "tags": [ "Policy Reporter" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Failing Policies by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_summary{status=\"Fail\"} > 0) by (exported_namespace)",
     "legendFormat": "{{`{{ exported_namespace }}`}}"
    }
   ]
  },
  {
   "title": "Failing ClusterPolicies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_summary{status=~\"Fail|Error\"} > 0) by (status)",
     "legendFormat": "{{`{{ status }}`}}"
    }
   ]
  },
  {
   "title": "Failing Policies Graph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{status=~\"fail|error\"} > 0) by (policy)",
     "legendFormat": "{{`{{ policy }}`}}"
    },
    {
     "expr": "sum(policy_report_result{status=~\"fail|error\"} > 0) by (policy)",
     "legendFormat": "{{`{{ policy }}`}}"
    }
   ]
  },
  {
   "title": "Failing PolicyRules",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(policy_report_result{status=~\"fail|error\"}) by (exported_namespace,policy,rule,kind,name,status)",
     "legendFormat": "{{`{{ exported_namespace }}`}}: {{`{{ policy }}`}}"
    }
   ]
  },
  {
   "title": "Failing ClusterPolicyRules",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "cluster_policy_report_result > 0",
     "legendFormat": "{{`{{ kind }}`}}: {{`{{ name }}`}} - {{`{{ policy }}`}}"
    }
   ]
  }
 ]
}