apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

commonLabels:
  app.kubernetes.io/instance: argo-events

resources:
- namespace.yaml
- rbac.yaml
- https://gitlab.okd.example.com/lab/okd-lab.git//gitops/manifests/argo-events?ref=HEAD
